### ISSUE TITLE
大佬这个怎么做到的啊

### ISSUE THREAD

**Issue by g0fcn** [flytam/blog#38]

**Comment by flytam** [comment]
可以看下这个 [link](https://blog.flytam.vip/%E6%89%93%E9%80%A0Github%20Issue%E5%88%B0Hexo%E9%83%A8%E7%BD%B2%E8%87%AA%E5%8A%A8%E5%B7%A5%E4%BD%9C%E6%B5%81.html)

**Comment by g0fcn** [comment]
我在知乎看到你文章了哈哈哈
